import type { Config } from "./types/index.ts"
import {
  km,
  raycast,
  alfred,
  shell,
  zed,
  zedToggle,
  linWidget,
} from "./types/index.ts"

export default {
  profile: {
    alone: 80,
    sim: 30,
  },

  simple: [{ from: "caps_lock", to: "escape" }],

  simlayers: {
    "semicolon-mode": { key: "semicolon", threshold: 250 },
    "quote-mode": { key: "quote", threshold: 250 },
    "backslash-mode": { key: "non_us_backslash", threshold: 250 },
    "1-mode": { key: "1", threshold: 250 },
    "2-mode": { key: "2", threshold: 250 },
    "3-mode": { key: "3", threshold: 250 },
    "4-mode": { key: "4", threshold: 250 },
    "5-mode": { key: "5", threshold: 250 },
    "7-mode": { key: "7", threshold: 250 },
    "8-mode": { key: "8", threshold: 250 },
    "9-mode": { key: "9", threshold: 250 },
    "0-mode": { key: "0", threshold: 250 },
    "hyphen-mode": { key: "hyphen", threshold: 250 },
    "equal-sign-mode": { key: "equal_sign", threshold: 250 },
    "tab-mode": { key: "tab", threshold: 250 },
    "q-mode": { key: "q", threshold: 250 },
    "w-mode": { key: "w", threshold: 250 },
    "e-mode": { key: "e", threshold: 250 },
    "r-mode": { key: "r", threshold: 250 },
    "t-mode": { key: "t", threshold: 250 },
    "u-mode": { key: "u", threshold: 250 },
    "y-mode": { key: "y", threshold: 250 },
    "i-mode": { key: "i", threshold: 250 },
    "o-mode": { key: "o", threshold: 250 },
    "p-mode": { key: "p", threshold: 250 },
    "open-bracket-mode": { key: "open_bracket", threshold: 250 },
    "close-bracket-mode": { key: "close_bracket", threshold: 250 },
    "a-mode": { key: "a", threshold: 250 },
    "s-mode": { key: "s", threshold: 250 },
    "d-mode": { key: "d", threshold: 250 },
    "f-mode": { key: "f", threshold: 250 },
    "g-mode": { key: "g", threshold: 250 },
    "escape-mode": { key: "escape", threshold: 250 },
    "tilde-mode": { key: "grave_accent_and_tilde", threshold: 250 },
    "z-mode": { key: "z", threshold: 250 },
    "x-mode": { key: "x", threshold: 250 },
    "c-mode": { key: "c", threshold: 250 },
    "v-mode": { key: "v", threshold: 250 },
    "b-mode": { key: "b", threshold: 250 },
    "n-mode": { key: "n", threshold: 250 },
    "m-mode": { key: "m", threshold: 250 },
    "comma-mode": { key: "comma", threshold: 250 },
    "dot-mode": { key: "period", threshold: 250 },
    "slash-mode": { key: "slash", threshold: 250 },
    "left-control-mode": { key: "left_control", threshold: 250 },
    "left-option-mode": { key: "left_option", threshold: 250 },
    "left-command-mode": { key: "left_command", threshold: 250 },
    "right-command-mode": { key: "right_command", threshold: 250 },
    "spacebar-mode": { key: "spacebar", threshold: 250 },
    "ts-mode": { key: "1", threshold: 250 },
    "go-mode": { key: "2", threshold: 250 },
    "py-mode": { key: "3", threshold: 250 },
    "swift-mode": { key: "6", threshold: 250 },
    "rust-mode": { key: "grave_accent_and_tilde", threshold: 250 },
  },

  rules: [
    // semicolon-mode: control for numbers, shift for letters
    {
      description: "colonkey (shift)",
      layer: "semicolon-mode",
      mappings: [
        { from: "1", to: { key: "1", modifiers: "left_control" } },
        { from: "2", to: { key: "2", modifiers: "left_control" } },
        { from: "3", to: { key: "3", modifiers: "left_control" } },
        { from: "4", to: { key: "4", modifiers: "left_control" } },
        { from: "5", to: { key: "5", modifiers: "left_control" } },
        { from: "6", to: { key: "6", modifiers: "left_control" } },
        { from: "7", to: { key: "7", modifiers: "left_control" } },
        { from: "8", to: { key: "8", modifiers: "left_control" } },
        { from: "9", to: { key: "9", modifiers: "left_control" } },
        { from: "q", to: { key: "q", modifiers: "left_shift" } },
        { from: "w", to: { key: "w", modifiers: "left_shift" } },
        { from: "e", to: { key: "e", modifiers: "left_shift" } },
        { from: "r", to: { key: "r", modifiers: "left_shift" } },
        { from: "t", to: { key: "t", modifiers: "left_shift" } },
        { from: "y", to: { key: "y", modifiers: "left_shift" } },
        { from: "u", to: { key: "u", modifiers: "left_shift" } },
        { from: "i", to: { key: "i", modifiers: "left_shift" } },
        { from: "o", to: { key: "o", modifiers: "left_shift" } },
        { from: "p", to: { key: "p", modifiers: "left_shift" } },
        { from: "escape", to: km("open: Notion") },
        { from: "a", to: { key: "a", modifiers: "left_shift" } },
        { from: "s", to: { key: "s", modifiers: "left_shift" } },
        { from: "d", to: { key: "d", modifiers: "left_shift" } },
        { from: "f", to: { key: "f", modifiers: "left_shift" } },
        { from: "g", to: { key: "g", modifiers: "left_shift" } },
        { from: "h", to: { key: "h", modifiers: "left_shift" } },
        { from: "j", to: { key: "j", modifiers: "left_shift" } },
        { from: "k", to: { key: "k", modifiers: "left_shift" } },
        { from: "l", to: { key: "l", modifiers: "left_shift" } },
        { from: "z", to: { key: "z", modifiers: "left_shift" } },
        { from: "x", to: { key: "x", modifiers: "left_shift" } },
        { from: "c", to: { key: "c", modifiers: "left_shift" } },
        { from: "v", to: { key: "v", modifiers: "left_shift" } },
        { from: "b", to: { key: "b", modifiers: "left_shift" } },
        { from: "n", to: { key: "n", modifiers: "left_shift" } },
        { from: "m", to: { key: "m", modifiers: "left_shift" } },
        { from: "grave_accent_and_tilde", to: km("enter: explain") },
        {
          from: "left_command",
          to: alfred("text_to_docs_and_text", "nikiv.flow"),
        },
        { from: "spacebar", to: km("open: Reflect") },
      ],
    },

    // s-mode: essential navigation and editing
    {
      description: "skey (essential)",
      layer: "s-mode",
      mappings: [
        {
          from: "w",
          to: [
            { key: "left_arrow", modifiers: "left_option" },
            { key: "right_arrow", modifiers: ["left_option", "left_shift"] },
          ],
        },
        { from: "e", to: "tab" },
        { from: "r", to: { key: "tab", modifiers: "left_shift" } },
        {
          from: "i",
          to: {
            key: "4",
            modifiers: ["left_control", "left_option", "left_command"],
          },
        },
        { from: "o", to: { key: "x", modifiers: "left_command" } },
        { from: "open_bracket", to: km("Lowercase selected text") },
        { from: "close_bracket", to: km("Uppercase selected text") },
        { from: "a", to: { key: "c", modifiers: "left_command" } },
        { from: "d", to: "delete_or_backspace" },
        { from: "f", to: "return_or_enter" },
        {
          from: "g",
          to: [{ key: "tab", modifiers: "left_command" }, "vk_none"],
        },
        { from: "h", to: "left_arrow" },
        { from: "j", to: "down_arrow" },
        { from: "k", to: "up_arrow" },
        { from: "l", to: "right_arrow" },
        {
          from: "semicolon",
          to: { key: "return_or_enter", modifiers: "left_shift" },
        },
        {
          from: "quote",
          to: [
            { key: "left_arrow", modifiers: "left_command" },
            { key: "right_arrow", modifiers: ["left_command", "left_shift"] },
          ],
        },
        {
          from: "c",
          to: { key: "delete_or_backspace", modifiers: "left_command" },
        },
        { from: "v", to: "left_shift" },
        { from: "b", to: { key: "left_arrow", modifiers: "left_command" } },
        { from: "n", to: { key: "v", modifiers: "left_command" } },
        { from: "m", to: { key: "right_arrow", modifiers: "left_command" } },
        {
          from: "period",
          to: {
            key: "y",
            modifiers: ["left_control", "left_option", "left_command"],
          },
        },
        { from: "slash", to: km("Make markdown link from selection {link}") },
        { from: "left_command", to: km("paste last flow cmd") },
        { from: "spacebar", to: zed("~/config/i/kar/config.ts") },
      ],
    },

    // swap : and ;
    {
      description: "swap : and ;",
      mappings: [
        {
          from: { key: "semicolon", modifiers: [] },
          to: { key: "semicolon", modifiers: "left_shift" },
        },
        { from: { key: "semicolon", modifiers: "shift" }, to: "semicolon" },
      ],
    },

    // simultaneous keys
    {
      description: "sim",
      mappings: [
        { from: ["j", "k"], to: km("open Safari new tab") },
        { from: ["k", "n"], to: km("open Comet new tab") },
        { from: ["k", "m"], to: km("New Linear task") },
        {
          from: ["j", "l"],
          to: { key: "spacebar", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: ["k", "l"],
          to: {
            key: "spacebar",
            modifiers: ["left_control", "left_option", "left_command"],
          },
        },
        {
          from: ["j", "semicolon"],
          to: {
            key: "9",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
        { from: ["l", "m"], to: raycast("nikivdev/flow/fork-internal-search") },
        { from: ["l", "n"], to: raycast("nikivdev/flow/index") },
      ],
    },

    // backslash-mode: sites
    {
      description: "backkey (sites)",
      layer: "backslash-mode",
      mappings: [
        { from: "c", to: km("w: CodeSandbox") },
        { from: "a", to: km("open: Val Town") },
        { from: "semicolon", to: km("w: Repl.it") },
      ],
    },

    // 1-mode: repo prompt
    {
      description: "1key (repo prompt)",
      layer: "1-mode",
      mappings: [
        { from: "f", to: km("repo prompt: flow") },
        { from: "j", to: km("repo prompt: 1f") },
        { from: "k", to: km("repo prompt: nikiv") },
        { from: "l", to: km("repo prompt: linsa") },
        { from: "semicolon", to: km("repo prompt: new") },
        { from: "spacebar", to: km("repo prompt: x") },
      ],
    },

    // 2-mode: move, searches
    {
      description: "2key (move, searches)",
      layer: "2-mode",
      mappings: [
        { from: "h", to: { key: "left_arrow", modifiers: "left_command" } },
        { from: "j", to: { key: "down_arrow", modifiers: "left_command" } },
        { from: "k", to: { key: "up_arrow", modifiers: "left_command" } },
        { from: "l", to: { key: "right_arrow", modifiers: "left_command" } },
        {
          from: "semicolon",
          to: { key: "up_arrow", modifiers: "left_option" },
        },
        { from: "quote", to: { key: "down_arrow", modifiers: "left_option" } },
      ],
    },

    // 3-mode: ports
    {
      description: "3key (ports)",
      layer: "3-mode",
      mappings: [
        { from: "r", to: km("arc: localhost:fr") },
        { from: "i", to: km("arc: localhost:linsa") },
        { from: "o", to: km("arc: localhost:la") },
        { from: "h", to: km("arc: localhost:ghost") },
        { from: "j", to: km("arc: localhost:3000") },
        { from: "k", to: km("arc: localhost:nikiv") },
        { from: "semicolon", to: km("arc: localhost:gen") },
        { from: "period", to: km("arc: localhost:api") },
        { from: "slash", to: km("arc: localhost:sb") },
        { from: "spacebar", to: km("arc: localhost:ui") },
      ],
    },

    // 4-mode: scroll
    {
      description: "4key ()",
      layer: "4-mode",
      mappings: [
        { from: "o", to: km("arc: scaleway.com") },
        { from: "j", to: { mouse_key: { vertical_wheel: 60 } } },
        { from: "k", to: { mouse_key: { vertical_wheel: -60 } } },
      ],
    },

    // 5-mode: language switching
    {
      description: "5key (swapping languages)",
      layer: "5-mode",
      mappings: [
        {
          from: "j",
          to: shell(
            'open -g "dash-plugin://query=.tsprofile%3A&prevent_activation=true"',
          ),
        },
        {
          from: "k",
          to: shell(
            'open "dash-plugin://query=.goprofile%3A&prevent_activation=true"',
          ),
        },
        {
          from: "n",
          to: shell(
            'open "dash-plugin://query=.pyprofile%3A&prevent_activation=true"',
          ),
        },
        {
          from: "3",
          to: shell(
            'open -g "dash-plugin://query=.rustprofile%3A&prevent_activation=true"',
          ),
        },
        {
          from: "spacebar",
          to: shell(
            'open "dash-plugin://query=.swiftprofile%3A&prevent_activation=true"',
          ),
        },
      ],
    },

    // 7-mode: gh workspaces
    {
      description: "7key (gh workspaces)",
      layer: "7-mode",
      mappings: [
        { from: "r", to: km("cursor: brush-gh") },
        { from: "f", to: km("cursor: folo-rs-gh") },
        { from: "c", to: km("cursor: calloop-rs-gh") },
        { from: "spacebar", to: km("cursor: model2vec-rs-gh") },
      ],
    },

    // 8-mode: gh workspaces
    {
      description: "8key (gh workspaces)",
      layer: "8-mode",
      mappings: [
        { from: "q", to: km("cursor: quic-go-gh") },
        { from: "e", to: km("cursor: elevenlabs-gh") },
        { from: "r", to: km("cursor: rig-gh") },
        { from: "s", to: km("cursor: goose-gh") },
        { from: "g", to: km("cursor: g3-gh") },
        { from: "k", to: km("cursor: anki-gh") },
        { from: "c", to: km("cursor: quiche-gh") },
        { from: "spacebar", to: km("cursor: fumadocs-gh") },
      ],
    },

    // 9-mode: gh workspaces
    {
      description: "9key (gh workspaces)",
      layer: "9-mode",
      mappings: [
        { from: "w", to: km("cursor: vscode-vim-gh") },
        { from: "t", to: km("cursor: typst-gh") },
        { from: "e", to: km("cursor: neovim-gh") },
        { from: "u", to: km("cursor: cuml-gh") },
        { from: "s", to: km("cursor: scipy-gh") },
        { from: "d", to: km("cursor: pandas-gh") },
        { from: "f", to: km("cursor: snafu-gh") },
        { from: "v", to: km("cursor: v8-gh") },
        { from: "spacebar", to: km("cursor: keel-gh") },
      ],
    },

    // hyphen-mode: gh workspaces
    {
      description: "hyphenkey (gh workspaces)",
      layer: "hyphen-mode",
      mappings: [
        { from: "e", to: km("cursor: phoenix-gh") },
        { from: "r", to: km("cursor: elixir-gh") },
        { from: "t", to: km("cursor: upstash-gh") },
        { from: "a", to: km("cursor: astro-gh") },
        { from: "s", to: km("cursor: scalar-gh") },
        { from: "d", to: km("cursor: caddy-gh") },
        { from: "f", to: km("cursor: traefik-gh") },
        { from: "g", to: km("cursor: godot-gh") },
        { from: "b", to: km("cursor: ladybird-gh") },
        { from: "x", to: km("cursor: xata-gh") },
        { from: "spacebar", to: km("cursor: morphic-gh") },
      ],
    },

    // hyphen-mode: more gh workspaces (second set)
    {
      description: "equalSignKey (gh workspaces)",
      layer: "hyphen-mode",
      mappings: [
        { from: "q", to: km("cursor: sqlight-gh") },
        { from: "w", to: km("cursor: swift-async-algorithms-gh") },
        { from: "e", to: km("cursor: lean-gh") },
        { from: "t", to: km("cursor: yugabyte-db-gh") },
        { from: "s", to: km("cursor: bolt-ts-gh") },
        { from: "f", to: km("cursor: fets-gh") },
        { from: "g", to: km("cursor: gptqmodel-gh") },
        { from: "c", to: km("cursor: curlie-gh") },
        { from: "t", to: km("cursor: streamlit-gh") },
        { from: "b", to: km("cursor: browser-bee-gh") },
        { from: "spacebar", to: km("cursor: n8n-gh") },
      ],
    },

    // tab-mode: sites
    {
      description: "tabkey (sites)",
      layer: "tab-mode",
      mappings: [
        { from: "w", to: km("arc: swift forum") },
        { from: "t", to: km("arc: t3 chat") },
        { from: "u", to: km("arc: soundcloud") },
        { from: "i", to: km("arc: le chat") },
        { from: "o", to: km("arc: bolt") },
        { from: "h", to: km("arc: producthunt") },
        { from: "j", to: km("arc: midjourney") },
        { from: "k", to: km("arc: grok imagine") },
        { from: "l", to: km("arc: sora") },
        { from: "semicolon", to: km("arc: backpack exchange") },
        { from: "c", to: km("arc: chef") },
        { from: "v", to: km("arc: vsco") },
        { from: "b", to: km("arc: uber") },
        { from: "n", to: km("arc: coinbase") },
        { from: "period", to: km("arc: elk") },
        { from: "spacebar", to: km("arc: gmail") },
      ],
    },

    // q-mode: cmd+shift
    {
      description: "qkey (cmd + shift)",
      layer: "q-mode",
      mappings: [
        {
          from: "3",
          to: { key: "3", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "4",
          to: { key: "4", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "5",
          to: { key: "5", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "6",
          to: { key: "6", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "7",
          to: { key: "7", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "8",
          to: { key: "8", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "9",
          to: { key: "9", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "0",
          to: { key: "0", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "w",
          to: { key: "w", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "e",
          to: { key: "e", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "r",
          to: { key: "r", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "t",
          to: { key: "t", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "y",
          to: { key: "y", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "u",
          to: { key: "u", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "i",
          to: { key: "i", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "o",
          to: { key: "o", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "p",
          to: { key: "p", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "open_bracket",
          to: {
            key: "open_bracket",
            modifiers: ["left_command", "left_shift"],
          },
        },
        {
          from: "close_bracket",
          to: {
            key: "close_bracket",
            modifiers: ["left_command", "left_shift"],
          },
        },
        {
          from: "a",
          to: { key: "a", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "s",
          to: { key: "s", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "d",
          to: { key: "d", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "f",
          to: { key: "f", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "g",
          to: { key: "g", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "h",
          to: { key: "h", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "j",
          to: { key: "j", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "k",
          to: { key: "k", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "l",
          to: { key: "l", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "semicolon",
          to: { key: "semicolon", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "quote",
          to: { key: "quote", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "z",
          to: { key: "z", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "x",
          to: { key: "x", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "c",
          to: { key: "c", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "v",
          to: { key: "v", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "b",
          to: { key: "b", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "n",
          to: { key: "n", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "m",
          to: { key: "m", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "comma",
          to: { key: "comma", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "period",
          to: { key: "period", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "slash",
          to: { key: "slash", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "spacebar",
          to: {
            key: "n",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
      ],
    },

    // w-mode: apps
    {
      description: "wkey (apps)",
      layer: "w-mode",
      mappings: [
        { from: "e", to: zed("~/code/nikiv") },
        { from: "r", to: km("open: 1Password") },
        { from: "t", to: km("open: Activity Monitor") },
        { from: "i", to: km("arc: n8n.io") },
        { from: "o", to: km("open: Keyboard Maestro") },
        { from: "escape", to: km("open: Finder") },
        { from: "a", to: km("open: Repo Prompt") },
        { from: "d", to: km("open: Fantastical") },
        { from: "f", to: km("open: Things") },
        { from: "h", to: km("open: Proxyman") },
        { from: "j", to: km("open: Ghostty") },
        { from: "k", to: km("open: Safari") },
        { from: "l", to: km("open: Zed") },
        { from: "semicolon", to: km("open: Cursor") },
        { from: "quote", to: km("open: JuxtaCode") },
        { from: "c", to: km("open: LM Studio") },
        { from: "v", to: km("open: Linear") },
        { from: "b", to: km("open: OrbStack") },
        { from: "n", to: km("open: Yaak") },
        { from: "m", to: km("open: TablePlus") },
        { from: "period", to: km("open: Xcode Beta") },
        { from: "slash", to: km("open: Sublime Merge") },
        { from: "left_command", to: km("zed: ~/config/fish/fn.fish") },
        { from: "spacebar", to: zed("~/config/i/lin/config.ts") },
      ],
      // { from: "g", to: km("open: Granola") },
      // { from: "i", to: km("open: Instruments") },
      // { from: "e", to: zed("~/code") }, // too much load on zed to load in code
      // { from: "semicolon", to: km("open: Electron") }, // todo: make 1f desktop & move it somewhere nice
    },

    // e-mode: cmd
    {
      description: "ekey (cmd)",
      layer: "e-mode",
      mappings: [
        { from: "q", to: { key: "q", modifiers: "left_command" } },
        { from: "w", to: { key: "w", modifiers: "left_command" } },
        { from: "r", to: { key: "r", modifiers: "left_command" } },
        { from: "t", to: { key: "t", modifiers: "left_command" } },
        { from: "u", to: { key: "u", modifiers: "left_command" } },
        { from: "i", to: { key: "i", modifiers: "left_command" } },
        { from: "p", to: { key: "p", modifiers: "left_command" } },
        {
          from: "open_bracket",
          to: { key: "open_bracket", modifiers: "left_command" },
        },
        {
          from: "close_bracket",
          to: { key: "close_bracket", modifiers: "left_command" },
        },
        {
          from: "semicolon",
          to: { key: "semicolon", modifiers: "left_command" },
        },
        { from: "quote", to: { key: "quote", modifiers: "left_command" } },
        { from: "comma", to: { key: "comma", modifiers: "left_command" } },
        { from: "period", to: { key: "period", modifiers: "left_command" } },
        { from: "slash", to: { key: "slash", modifiers: "left_command" } },
        { from: "escape", to: zed("~/config/zed/settings.json") },
        { from: "a", to: { key: "a", modifiers: "left_command" } },
        { from: "b", to: { key: "b", modifiers: "left_command" } },
        { from: "c", to: { key: "c", modifiers: "left_command" } },
        { from: "d", to: { key: "d", modifiers: "left_command" } },
        { from: "f", to: { key: "f", modifiers: "left_command" } },
        { from: "g", to: { key: "g", modifiers: "left_command" } },
        { from: "h", to: { key: "h", modifiers: "left_command" } },
        { from: "j", to: { key: "j", modifiers: "left_command" } },
        { from: "k", to: { key: "k", modifiers: "left_command" } },
        { from: "l", to: { key: "l", modifiers: "left_command" } },
        { from: "m", to: { key: "m", modifiers: "left_command" } },
        { from: "n", to: { key: "n", modifiers: "left_command" } },
        { from: "o", to: { key: "o", modifiers: "left_command" } },
        { from: "s", to: { key: "s", modifiers: "left_command" } },
        { from: "v", to: { key: "v", modifiers: "left_command" } },
        { from: "x", to: { key: "x", modifiers: "left_command" } },
        { from: "y", to: { key: "y", modifiers: "left_command" } },
        { from: "z", to: { key: "z", modifiers: "left_command" } },
        { from: "1", to: { key: "1", modifiers: "left_command" } },
        { from: "2", to: { key: "2", modifiers: "left_command" } },
        { from: "3", to: { key: "3", modifiers: "left_command" } },
        { from: "4", to: { key: "4", modifiers: "left_command" } },
        { from: "5", to: { key: "5", modifiers: "left_command" } },
        { from: "6", to: { key: "6", modifiers: "left_command" } },
        { from: "7", to: { key: "7", modifiers: "left_command" } },
        { from: "8", to: { key: "8", modifiers: "left_command" } },
        { from: "9", to: { key: "9", modifiers: "left_command" } },
        { from: "0", to: { key: "0", modifiers: "left_command" } },
        // { from: "left_command", to: km("get last cmd output & paste it") },
        // { from: "spacebar", to: km("zed: ~/.config/lin/config.ts") },
        // { from: "left_command", to: km("live on/off") }, // todo: breaks, move it to w+left_cmd when it works better
        {
          from: "spacebar",
          to: { key: "spacebar", modifiers: "left_command" },
        },
        // {
        //   from: "spacebar",
        //   to: {
        //     key: "c",
        //     modifiers: ["left_command", "left_option", "left_shift"],
        //   },
        // },
      ],
    },

    // r-mode: apps
    {
      description: "rkey (apps)",
      layer: "r-mode",
      mappings: [
        { from: "tab", to: km("open: Transmission") },
        { from: "q", to: km("open: System Settings: Network") },
        { from: "w", to: km("open: IINA") },
        { from: "e", to: km("open: System Settings") },
        { from: "i", to: km("open: Voice Memos") },
        { from: "l", to: km("open: Lightroom") },
        { from: "p", to: km("open: PDF Expert") },
        { from: "a", to: km("open: Alfred Preferences") },
        { from: "s", to: km("open: OBS") },
        { from: "b", to: km("Edit keyboard shortcuts") },
        { from: "j", to: km("open: Photos") },
        { from: "k", to: km("open: Music") },
        { from: "semicolon", to: km("open: DaVinci Resolve") },
        { from: "n", to: km("open: Blender") },
        { from: "m", to: km("open: Darkroom") },
        { from: "period", to: km("open: Final Cut Pro") },
        { from: "slash", to: km("open: Developer") },
      ],
    },

    // t-mode: sites
    {
      description: "tkey (sites)",
      layer: "t-mode",
      mappings: [
        { from: "w", to: km("arc: wikipedia") },
        { from: "u", to: km("arc: upstash") },
        { from: "i", to: km("arc: tiktok.com") },
        { from: "p", to: km("arc: glass.photo") },
        { from: "a", to: km("arc: amazon") },
        { from: "s", to: km("arc: etsy") },
        { from: "h", to: km("arc: news.ycombinator.com") },
        { from: "j", to: km("arc: threads.com") },
        { from: "k", to: km("arc: farcaster") },
        { from: "l", to: km("arc: bluesky") },
        { from: "semicolon", to: km("arc: twitch") },
        { from: "quote", to: km("arc: strava") },
        { from: "b", to: km("arc: lobsters") },
        { from: "n", to: km("arc: pinterest.com") },
        { from: "m", to: km("arc: cosmos.co") },
        { from: "period", to: km("arc: substack.com") },
        { from: "slash", to: km("arc: alltrails") },
        { from: "spacebar", to: km("arc: linkedin.com") },
      ],
    },

    // u-mode: sites
    {
      description: "ukey (sites)",
      layer: "u-mode",
      mappings: [
        { from: "q", to: km("arc: qwen") },
        { from: "w", to: km("arc: github map") },
        { from: "e", to: km("arc: gel") },
        { from: "r", to: km("arc: arxiv") },
        { from: "i", to: km("arc: pinboard (popular)") },
        { from: "escape", to: km("arc: vercel domains") },
        { from: "s", to: km("arc: vs") },
        { from: "d", to: km("arc: map of reddit") },
        { from: "f", to: km("arc: cronometer") },
        { from: "x", to: km("arc: science explore") },
        { from: "c", to: km("arc: convex") },
        { from: "v", to: km("arc: elevenlabs") },
        { from: "b", to: km("arc: grafbase") },
        { from: "spacebar", to: km("arc: rutracker") },
      ],
    },

    // y-mode: gh workspaces
    {
      description: "ykey (gh workspaces)",
      layer: "y-mode",
      mappings: [
        { from: "w", to: km("cursor: workos-gh") },
        { from: "i", to: km("cursor: builder-gh") },
        { from: "u", to: km("cursor: mycloudkit-gh") },
        { from: "o", to: km("cursor: leptos-gh") },
        { from: "p", to: km("cursor: spark-gh") },
        { from: "h", to: km("cursor: authkit-gh") },
        { from: "f", to: km("cursor: ffmpeg-gh") },
        { from: "k", to: km("cursor: kanidm-gh") },
        { from: "l", to: km("cursor: litellm-gh") },
        { from: "semicolon", to: km("cursor: markdoc-gh") },
        { from: "b", to: km("cursor: obs-studio-gh") },
        { from: "n", to: km("cursor: ferron-gh") },
        { from: "m", to: km("cursor: axum-gh") },
        { from: "period", to: km("cursor: solidis-gh") },
      ],
    },

    // i-mode: symbols
    {
      description: "ikey (symbols)",
      layer: "i-mode",
      mappings: [
        { from: "1", to: { key: "1", modifiers: "left_shift" } },
        { from: "2", to: { key: "2", modifiers: "left_shift" } },
        { from: "3", to: { key: "equal_sign", modifiers: "left_shift" } },
        { from: "4", to: { key: "8", modifiers: "left_shift" } },
        { from: "w", to: { key: "9", modifiers: "left_shift" } },
        { from: "e", to: { key: "3", modifiers: "left_shift" } },
        { from: "q", to: { key: "open_bracket", modifiers: "left_shift" } },
        {
          from: "escape",
          to: { key: "open_bracket", modifiers: "left_shift" },
        },
        { from: "left_command", to: km("explain (selection, or paste)") },
        { from: "r", to: { key: "quote", modifiers: "left_shift" } },
        { from: "t", to: "quote" },
        { from: "o", to: "open_bracket" },
        { from: "p", to: "close_bracket" },
        {
          from: "open_bracket",
          to: { key: "close_bracket", modifiers: "left_shift" },
        },
        { from: "a", to: "slash" },
        { from: "s", to: { key: "hyphen", modifiers: "left_shift" } },
        { from: "d", to: "backslash" },
        { from: "f", to: "hyphen" },
        { from: "g", to: { key: "4", modifiers: "left_shift" } },
        { from: "h", to: km("paste: €") },
        { from: "j", to: "equal_sign" },
        {
          from: "l",
          to: [
            "hyphen",
            { key: "period", modifiers: "left_shift" },
            "spacebar",
          ],
        },
        { from: "semicolon", to: "semicolon" },
        {
          from: "grave_accent_and_tilde",
          to: { key: "grave_accent_and_tilde", modifiers: "left_shift" },
        },
        { from: "z", to: { key: "slash", modifiers: "left_shift" } },
        { from: "x", to: { key: "backslash", modifiers: "left_shift" } },
        { from: "c", to: { key: "7", modifiers: "left_shift" } },
        { from: "v", to: { key: "comma", modifiers: "left_shift" } },
        { from: "b", to: ["slash", "slash", "spacebar"] },
      ],
    },

    // o-mode: things
    {
      description: "okey (things)",
      layer: "o-mode",
      mappings: [
        { from: "1", to: { key: "1", modifiers: "left_command" } },
        { from: "2", to: { key: "2", modifiers: "left_command" } },
        { from: "3", to: { key: "3", modifiers: "left_command" } },
        { from: "4", to: { key: "4", modifiers: "left_command" } },
        { from: "5", to: { key: "5", modifiers: "left_command" } },
        { from: "6", to: { key: "6", modifiers: "left_command" } },
        { from: "w", to: km("arc: aws.amazon.com") },
        { from: "e", to: km("arc: vercel.com") },
        { from: "a", to: km("arc: expo") },
        { from: "s", to: km("arc: console.neon.tech") },
        { from: "d", to: km("arc: yandex.cloud") },
        { from: "f", to: km("arc: console.cloud.google.com") },
        { from: "j", to: km("arc: jazz inspector") },
        { from: "z", to: km("arc: deepseek") },
        {
          from: "c",
          to: raycast("raycast/emoji-symbols/search-emoji-symbols"),
        },
        { from: "m", to: km("arc: jazz dashboard") },
        { from: "spacebar", to: km("arc: app.planetscale.com") },
      ],
    },

    // open-bracket-mode: gh workspaces
    {
      description: "openBracketKey (gh workspaces)",
      layer: "open-bracket-mode",
      mappings: [
        { from: "w", to: km("cursor: tldraw-gh") },
        { from: "e", to: km("cursor: electric-gh") },
        { from: "r", to: km("cursor: rive-gh") },
        { from: "t", to: km("cursor: stripe-gh") },
        { from: "u", to: km("cursor: kunkun-gh") },
        { from: "i", to: km("cursor: vite-gh") },
        { from: "o", to: km("cursor: solid-gh") },
        { from: "s", to: km("cursor: liveblocks-gh") },
        { from: "f", to: km("cursor: codemirror-gh") },
        { from: "g", to: km("cursor: pglite-gh") },
        { from: "j", to: km("cursor: laminar-gh") },
        { from: "k", to: km("cursor: kunkun-gh") },
        { from: "z", to: km("cursor: zero-gh") },
        { from: "x", to: km("cursor: axiom-gh") },
        { from: "v", to: km("cursor: devenv-gh") },
        { from: "b", to: km("cursor: tinybase-gh") },
        { from: "n", to: km("cursor: instantdb-gh") },
        { from: "m", to: km("cursor: automerge-gh") },
        { from: "spacebar", to: km("cursor: lightning-ai-gh") },
      ],
    },

    // close-bracket-mode: gh workspaces
    {
      description: "closeBracketKey (gh workspaces)",
      layer: "close-bracket-mode",
      mappings: [
        { from: "w", to: km("cursor: wrpc-gh") },
        { from: "e", to: km("cursor: muscle-mem-gh") },
        { from: "r", to: km("cursor: stack-error-rs-gh") },
        { from: "a", to: km("cursor: nats-gh") },
        { from: "s", to: km("cursor: timescale-gh") },
        { from: "d", to: km("cursor: wit-deps-gh") },
        { from: "f", to: km("cursor: kafka-gh") },
        { from: "spacebar", to: km("cursor: river-gh") },
      ],
    },

    // a-mode: ctrl
    {
      description: "akey (ctrl)",
      layer: "a-mode",
      mappings: [
        { from: "2", to: { key: "2", modifiers: "left_control" } },
        { from: "3", to: { key: "3", modifiers: "left_control" } },
        { from: "4", to: { key: "4", modifiers: "left_control" } },
        { from: "5", to: { key: "5", modifiers: "left_control" } },
        { from: "6", to: { key: "6", modifiers: "left_control" } },
        { from: "7", to: { key: "7", modifiers: "left_control" } },
        { from: "8", to: { key: "8", modifiers: "left_control" } },
        { from: "9", to: { key: "9", modifiers: "left_control" } },
        { from: "0", to: { key: "0", modifiers: "left_control" } },
        { from: "q", to: { key: "q", modifiers: "left_control" } },
        { from: "w", to: { key: "w", modifiers: "left_control" } },
        { from: "e", to: { key: "e", modifiers: "left_control" } },
        { from: "r", to: { key: "r", modifiers: "left_control" } },
        { from: "t", to: { key: "t", modifiers: "left_control" } },
        { from: "i", to: { key: "i", modifiers: "left_control" } },
        { from: "o", to: { key: "o", modifiers: "left_control" } },
        { from: "y", to: { key: "y", modifiers: "left_control" } },
        { from: "u", to: { key: "u", modifiers: "left_control" } },
        { from: "p", to: { key: "p", modifiers: "left_control" } },
        {
          from: "open_bracket",
          to: { key: "open_bracket", modifiers: "left_control" },
        },
        {
          from: "close_bracket",
          to: { key: "close_bracket", modifiers: "left_control" },
        },
        { from: "s", to: { key: "s", modifiers: "left_control" } },
        { from: "d", to: { key: "d", modifiers: "left_control" } },
        { from: "f", to: { key: "f", modifiers: "left_control" } },
        { from: "g", to: { key: "g", modifiers: "left_control" } },
        { from: "h", to: { key: "h", modifiers: "left_control" } },
        { from: "j", to: { key: "j", modifiers: "left_control" } },
        { from: "k", to: { key: "k", modifiers: "left_control" } },
        { from: "l", to: { key: "l", modifiers: "left_control" } },
        {
          from: "semicolon",
          to: { key: "semicolon", modifiers: "left_control" },
        },
        { from: "quote", to: { key: "quote", modifiers: "left_control" } },
        { from: "z", to: { key: "z", modifiers: "left_control" } },
        { from: "x", to: { key: "x", modifiers: "left_control" } },
        { from: "c", to: { key: "c", modifiers: "left_control" } },
        { from: "v", to: { key: "v", modifiers: "left_control" } },
        { from: "b", to: { key: "b", modifiers: "left_control" } },
        { from: "n", to: { key: "n", modifiers: "left_control" } },
        { from: "m", to: { key: "m", modifiers: "left_control" } },
        { from: "comma", to: { key: "comma", modifiers: "left_control" } },
        { from: "period", to: { key: "period", modifiers: "left_control" } },
        { from: "slash", to: { key: "slash", modifiers: "left_control" } },
        {
          from: "left_command",
          to: {
            key: "spacebar",
            modifiers: ["left_command", "left_shift", "left_control"],
          },
        },
        {
          from: "spacebar",
          to: { key: "spacebar", modifiers: ["left_shift", "left_option"] },
        },
      ],
    },

    // d-mode: mouse/media
    {
      description: "dkey (mouse)",
      layer: "d-mode",
      mappings: [
        { from: "v", to: { pointing_button: "button1" } },
        { from: "b", to: { pointing_button: "button3" } },
        { from: "z", to: { pointing_button: "button2" } },
        { from: "tab", to: "mute" },
        { from: "q", to: "illumination_decrement" },
        { from: "w", to: "illumination_increment" },
        { from: "e", to: "display_brightness_decrement" },
        { from: "i", to: { key: "keypad_hyphen", modifiers: "left_command" } },
        { from: "o", to: { key: "keypad_plus", modifiers: "left_command" } },
        { from: "escape", to: "display_brightness_increment" },
        { from: "a", to: km("arc: grok.com") },
        { from: "s", to: km("Selection -> Claude") },
        {
          from: "f",
          to: { key: "return_or_enter", modifiers: "left_command" },
        },
        { from: "h", to: "vk_consumer_previous" },
        { from: "j", to: km("arc: cloudflare.com") },
        { from: "k", to: "vk_consumer_play" },
        { from: "l", to: "vk_consumer_next" },
        { from: "semicolon", to: km("open: Spotify (or search)") },
        { from: "n", to: "volume_decrement" },
        { from: "m", to: "volume_increment" },
        { from: "period", to: km("New Linear task") },
        {
          from: "comma",
          to: {
            key: "1",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "spacebar",
          to: { key: "9", modifiers: ["left_command", "left_control"] },
        },
      ],
    },

    // f-mode: essential
    {
      description: "fkey (essential)",
      layer: "f-mode",
      mappings: [
        { from: "1", to: km("View Sip") },
        { from: "q", to: km("arc: framer.com") },
        { from: "w", to: km("open: Figma Beta") },
        {
          from: "e",
          to: { key: "8", modifiers: ["left_command", "left_option"] },
        },
        { from: "r", to: km("Centre mouse to active app") },
        { from: "tab", to: km("open: tldraw") },
        { from: "a", to: km("open: Chrome Canary") },
        { from: "s", to: km("open: Safari Technology Preview") },
        { from: "d", to: km("open: Discord (in Arc)") },
        // { from: "h", to: km("open: Focus") }, // todo: move this to 1focus proper
        {
          from: "j",
          to: {
            key: "3",
            modifiers: ["left_control", "left_command"],
          },
        },
        {
          from: "k",
          to: {
            key: "close_bracket",
            modifiers: ["left_control", "left_option", "left_command"],
          },
        },
        { from: "l", to: km("open: Claude") },
        {
          from: "semicolon",
          to: km(
            "switch between windows of same app (or switch to another app if no more than 1 window)",
          ),
        },
        { from: "u", to: km("telegram: log") },
        { from: "i", to: km("telegram: nikivdev") },
        { from: "o", to: km("new X post (in Arc)") },
        {
          from: "z",
          to: {
            key: "backslash",
            modifiers: ["left_control", "left_option", "left_command"],
          },
        },
        { from: "n", to: km("arc: railway.com") },
        { from: "m", to: km("arc: modal.com") },
        { from: "period", to: km("open: ChatGPT") },
        { from: "grave_accent_and_tilde", to: km("open: Chrome Canary") },
        { from: "spacebar", to: km("open: Eagle") },
      ],
    },

    // g-mode: actions/window management
    {
      description: "gkey (actions)",
      layer: "g-mode",
      mappings: [
        {
          from: "w",
          to: {
            key: "grave_accent_and_tilde",
            modifiers: ["left_command", "left_shift"],
          },
        },
        {
          from: "caps_lock",
          to: km("Go to KM group of current app from picklist"),
        },
        { from: "a", to: km("Go to KM group of current app") },
        { from: "d", to: km("Dismiss notifications") },
        {
          from: "h",
          to: {
            key: "a",
            modifiers: ["left_command", "left_shift", "left_option"],
          },
        },
        {
          from: "j",
          to: { key: "slash", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "k",
          to: {
            key: "f",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
        {
          from: "l",
          to: {
            key: "d",
            modifiers: ["left_command", "left_shift", "left_option"],
          },
        },
        {
          from: "semicolon",
          to: {
            key: "s",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
        {
          from: "u",
          to: {
            key: "7",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "i",
          to: {
            key: "6",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "n",
          to: {
            key: "4",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "m",
          to: {
            key: "3",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "comma",
          to: {
            key: "5",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "quote",
          to: {
            key: "6",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
        {
          from: "spacebar",
          to: {
            key: "u",
            modifiers: ["left_command", "left_option", "left_shift"],
          },
        },
      ],
    },

    // escape-mode: sites
    {
      description: "capskey",
      layer: "escape-mode",
      mappings: [
        { from: "q", to: km("arc: console.groq.com") },
        { from: "w", to: km("arc: hetzner.com") },
        { from: "e", to: km("arc: maps.google.com") },
        { from: "r", to: km("arc: resend.com") },
        { from: "s", to: km("arc: stripe.com") },
        { from: "d", to: km("arc: cloud.cerebras.ai") },
        { from: "f", to: km("arc: v0.app") },
        { from: "j", to: km("arc: primeintellect.ai") },
        { from: "k", to: km("arc: openrouter.ai") },
        { from: "l", to: km("arc: huggingface.com") },
        { from: "semicolon", to: km("arc: clickhouse") },
        { from: "n", to: km("arc: tinker-console.thinkingmachines.ai") },
        { from: "m", to: km("arc: fal.ai") },
        { from: "period", to: km("arc: leap.new") },
        { from: "spacebar", to: km("arc: sentry.com") },
      ],
    },

    // tilde-mode: pastes and sites
    {
      description: "tilkey ()",
      layer: "tilde-mode",
      mappings: [
        { from: "q", to: km("paste: personal nikita@ email") },
        { from: "w", to: km("paste: personal nikita.vo@ email") },
        { from: "e", to: km("arc: axiom.com") },
        { from: "r", to: km("arc: daytona.com") },
        { from: "i", to: km("paste: Cal.com (15 min)") },
        {
          from: "o",
          to: {
            key: "0",
            modifiers: ["left_control", "left_shift", "left_command"],
          },
        },
        { from: "n", to: km("telegram: nikivdev") },
        { from: "m", to: km("telegram: nikivdev (chat)") },
        { from: "s", to: km("enter: what to run next?") },
        { from: "d", to: km("paste: what flow.toml task to run ") },
        { from: "f", to: km("paste: create flow.toml task ") },
        { from: "h", to: km("New KM global macro") },
        { from: "j", to: km("Test") },
        { from: "k", to: km("Go to test macro") },
        { from: "l", to: alfred("run", "iansinnott.keyboardmaestro") },
        { from: "semicolon", to: raycast("loris/safari/search-history") },
        { from: "c", to: km("arc: dashboard.electric-sql.cloud") },
        { from: "b", to: km("arc: reddit.com (upvotes)") },
        { from: "comma", to: km("enter: write docs/how-it-works.md") },
        { from: "period", to: km("arc: x.com (bookmarks)") },
        { from: "slash", to: km("arc: x.com (likes)") },
        { from: "left_command", to: km("paste: create cmd in flow where ") },
      ],
    },

    // z-mode: communication
    {
      description: "zkey ()",
      layer: "z-mode",
      mappings: [
        { from: "w", to: km("Create new contact") },
        { from: "e", to: km("open: Zoom") },
        { from: "d", to: km("New Spark email") },
        { from: "f", to: km("open: Spark") },
        { from: "j", to: km("arc: localhost:gen") },
        { from: "k", to: km("arc: localhost:nikiv") },
        { from: "l", to: km("arc: localhost:linsa") },
        { from: "semicolon", to: km("arc: localhost:1f") },
        { from: "quote", to: km("arc: localhost:genx") },
        { from: "c", to: km("open: Chattti") },
        { from: "v", to: km("open: Simulator") },
        { from: "n", to: km("arc: localhost:sb") },
        { from: "m", to: km("arc: localhost:la") },
        { from: "period", to: km("arc: localhost:gitedit") },
        { from: "slash", to: km("arc: localhost:as") },
        { from: "spacebar", to: km("use ai") },
      ],
    },

    // x-mode: zed workspaces
    {
      description: "xkey ()",
      layer: "x-mode",
      mappings: [
        { from: "l", to: km("zed: LMCache") },
        { from: "k", to: km("zed: karabiner") },
        { from: "j", to: km("zed: jax") },
      ],
    },

    {
      description: "ckey ()",
      layer: "c-mode",
      mappings: [
        { from: "w", to: zed("~/repos/encoredev/encore") },
        { from: "e", to: zed("~/repos/Effect-TS/effect") },
        { from: "i", to: zed("~/code/lang/zig") },
        { from: "o", to: zed("~/repos/tarantool/tarantool") },
        { from: "escape", to: zed("~/code/lang/cpp") },
        { from: "a", to: zed("~/repos/reatom/reatom") },
        { from: "s", to: zed("~/code/lang/swift") },
        { from: "d", to: zed("~/repos/midday-ai/midday") },
        { from: "j", to: zed("~/code/lang/ts") },
        { from: "k", to: zed("~/code/lang/mbt") },
        { from: "l", to: zed("~/code/lang/py") },
        { from: "semicolon", to: zed("~/code/lang/go") },
        { from: "n", to: zed("~/repos/badlogic/pi-mono") },
        { from: "m", to: zed("~/repos/TanStack/ai") },
        { from: "period", to: zed("~/repos/microsoft/vscode") },
        { from: "spacebar", to: zed("~/code/lang/rust") },
      ],
      // { from: "w", to: km("warp: swift") },
      // { from: "e", to: km("warp: ts") },
      // { from: "i", to: km("warp: riplay") },
      // { from: "o", to: km("warp: go") },
      // { from: "escape", to: km("warp: train") }, // todo: moved to v+m in zed
      // { from: "a", to: km("warp: py") },
      // { from: "s", to: km("warp: config") },
      // { from: "d", to: km("warp: lin-ios") },
      // { from: "k", to: km("warp: new") },
      // { from: "l", to: km("warp: linsa") },
      // { from: "semicolon", to: km("warp: 1f") },
      // { from: "n", to: km("warp: gitedit") },
      // { from: "m", to: km("warp: glide") },
      // { from: "period", to: km("warp: mbt") },
      // { from: "spacebar", to: km("warp: infra") },
      // { from: "spacebar", to: km("warp: x") },
      // { from: "r", to: km("warp: try") },
      // { from: "right_command", to: km("warp: mojo") },
      // { from: "comma", to: km("warp: ai") },
      // { from: "grave_accent_and_tilde", to: km("warp: focus") },
      // { from: "quote", to: km("warp: genx") },
      // { from: "f", to: km("warp: 1f-vscode") },
      // { from: "u", to: km("warp: elixir") },
      // { from: "tab", to: km("warp: cpp") },
    },

    // v-mode: search
    {
      description: "vkey ()",
      layer: "v-mode",
      mappings: [
        { from: "w", to: zed("~/repos/raycast/extensions") },
        { from: "e", to: zed("~/repos/garden-co/jazz2") },
        { from: "r", to: zed("~/code/friendik") },
        { from: "i", to: zed("~/code/infra") },
        { from: "o", to: zed("~/code/org/gitedit/gitedit") },
        { from: "a", to: zed("~/code/alfred") },
        { from: "s", to: zed("~/code/org/gen/new") },
        { from: "d", to: zed("~/code/ai") },
        { from: "f", to: zed("~/code/org/1f/1f") },
        {
          from: "j",
          to: alfred("nikiv.dev.flow", "code"),
        },
        {
          from: "k",
          to: alfred("nikiv.dev.flow", "repos"),
        },
        { from: "l", to: zed("~/code/org/linsa/linsa") },
        { from: "semicolon", to: zed("~/code/flow") },
        { from: "grave_accent_and_tilde", to: zed("~/code/telegram") },
        { from: "z", to: zed("~/code/org/la/la") },
        { from: "x", to: zed("~/code/x") },
        { from: "b", to: zed("~/code/x/db") },
        { from: "n", to: zed("~/code/zerg") },
        { from: "m", to: zed("~/code/org/linsa/lin") },
        { from: "period", to: zed("~/code/myflow") },
        { from: "spacebar", to: zed("~/repos/0xPlaygrounds/rig") },
      ],
      // { from: "left_command", to: zed("~/code/org/1f/sdk") },
      // { from: "h", to: zed("~/code/org/gen/train") },
      // { from: "i", to: zed("~/repos/cloudflare/agents") },
      // { from: "o", to: zed("~/repos/agno-agi/agno") },
      // { from: "n", to: km("warp: lin") },
      // { from: "semicolon", to: km("warp: flow") },
      // { from: "n", to: zed("~/") },
      // { from: "a", to: zed("~/repos/lisyarus/webgpu-raytracer") },
      // { from: "q", to: km("zed: cpp") },
      // { from: "w", to: km("zed: flow") },
      // { from: "e", to: zed("~/lang/ts") },
      // { from: "r", to: km("zed: try") },
      // { from: "i", to: km("zed: glide") },
      // { from: "o", to: km("zed: infra") },
      // { from: "p", to: km("zed: riplay") },
      // { from: "escape", to: km("zed: la") },
      // { from: "a", to: km("zed: rust") },
      // { from: "s", to: km("zed: train") },
      // { from: "j", to: km("zed: lin") },
      // { from: "k", to: km("zed: nikiv") },
      // { from: "l", to: km("zed: linsa") },
      // { from: "semicolon", to: km("zed: 1f") },
      // { from: "quote", to: km("zed: genx") },
      // { from: "grave_accent_and_tilde", to: km("zed: infra") },
      // { from: "z", to: km("zed: py") },
      // { from: "x", to: km("zed: xx") },
      // { from: "n", to: km("zed: lin-ios") },
      // { from: "m", to: km("zed: new") },
      // { from: "comma", to: km("zed: ai") },
      // { from: "period", to: km("zed: gitedit") },
      // { from: "slash", to: km("zed: config") },
      // { from: "left_command", to: km("zed: swift") },
      // { from: "spacebar", to: km("zed: x") },
      // { from: "right_command", to: km("zed: mojo") },
    },

    // b-mode: editing
    {
      description: "bkey ()",
      layer: "b-mode",
      mappings: [
        { from: "h", to: km("edit: GitHub Bio") },
        {
          from: "j",
          to: linWidget("~/config/i/kar/widgets/sf-time.ts", { ttlMs: 2000 }),
        },
        // todo: fix
        {
          from: "k",
          to: alfred(
            "list_windows_of_active_app",
            "com.alfredapp.vitor.windowswitcher",
          ),
        },
        {
          from: "semicolon",
          to: km("paste url of currently playing spotify song"),
        },
        { from: "period", to: km("paste currently playing spotify song") },
      ],
    },

    {
      description: "nkey (pages)",
      layer: "n-mode",
      mappings: [
        { from: "1", to: { key: "1", modifiers: "left_option" } },
        { from: "2", to: { key: "2", modifiers: "left_option" } },
        { from: "3", to: { key: "3", modifiers: "left_option" } },
        { from: "4", to: { key: "4", modifiers: "left_option" } },
        { from: "5", to: { key: "5", modifiers: "left_option" } },
        { from: "6", to: { key: "6", modifiers: "left_option" } },
        { from: "q", to: km("reflect: Grow") },
        { from: "w", to: km("reflect: Events") },
        { from: "e", to: km("reflect: Learn") },
        { from: "r", to: km("reflect: Raise") },
        { from: "t", to: km("reflect: Nutrition") },
        { from: "o", to: km("reflect: Jobs") },
        { from: "escape", to: km("reflect: Hire") },
        // { from: "a", to: km("reflect: Plan") },
        // { from: "a", to: km("reflect: Think") }, // todo: move this to glide better (bike + figma like thing)
        { from: "a", to: km("reflect: Journal") },
        { from: "s", to: km("reflect: Health") },
        { from: "d", to: km("reflect: Read") },
        { from: "f", to: km("Search Reflect") },
        { from: "g", to: km("reflect: Projects") },
        { from: "k", to: km("reflect: Music") },
        { from: "l", to: km("reflect: Photos") },
        { from: "semicolon", to: km("reflect: Family") },
        { from: "grave_accent_and_tilde", to: km("reflect: Invest") },
        { from: "z", to: km("reflect: Meet") },
        { from: "x", to: km("reflect: Pretty") },
        { from: "c", to: km("reflect: Costs") },
        { from: "v", to: km("reflect: Love") },
        { from: "b", to: km("reflect: Buy") },
        { from: "left_command", to: km("reflect: Habits") },
        { from: "spacebar", to: zed("~/config/i/test.md") },
        { from: "period", to: km("reflect: Move") },
      ],
    },

    // m-mode: zed workspaces
    {
      description: "mkey ()",
      layer: "m-mode",
      mappings: [
        { from: "w", to: zed("~/repos/expo/expo") },
        { from: "e", to: zed("~/repos/electron/electron") },
        { from: "r", to: zed("~/code/kar") },
        { from: "t", to: zed("~/repos/tailscale/tailscale") },
        { from: "escape", to: zed("~/repos/typesense/typesense") },
        { from: "a", to: zed("~/repos/alchemy-run/alchemy") },
        { from: "s", to: zed("~/repos/clawdbot/clawdbot") },
        { from: "d", to: zed("~/repos/denoland/std") },
        { from: "f", to: zed("~/repos/jj-vcs/jj") },
        { from: "g", to: zed("~/repos/GitoxideLabs/gitoxide") },
        { from: "grave_accent_and_tilde", to: zed("~/repos/banteg/takopi") },
        { from: "z", to: zed("~/repos/HazelChat/hazel") },
        { from: "c", to: zed("~/repos/wannabespace/conar") },
        { from: "spacebar", to: zed("~/repos/openai/codex") },
      ],
      // { from: "w", to: km("zed: verifiers") },
      // { from: "e", to: km("zed: codex") },
      // { from: "t", to: km("zed: tuist") },
      // { from: "s", to: km("zed: electron") },
      // { from: "d", to: km("zed: mlx") },
      // { from: "grave_accent_and_tilde", to: km("zed: opentinker") },
      // { from: "z", to: km("zed: agno") },
      // { from: "x", to: km("zed: electric") },
      // { from: "x", to: km("zed: jax-js") },
      // { from: "c", to: km("zed: llama.cpp") },
      // { from: "v", to: km("zed: encore") },
      // { from: "b", to: km("zed: obs") },
    },

    // dot-mode: zed workspaces
    {
      description: "dotkey ()",
      layer: "dot-mode",
      mappings: [
        { from: "w", to: zed("~/repos/garden-co/jazz") },
        {
          from: "e",
          to: zed("~/repos/Dimillian/CodexMonitor"),
        },
        { from: "r", to: zed("~/repos/fuma-nama/fumadocs") },
        { from: "escape", to: zed("~/repos/elysiajs/elysia") },
        { from: "a", to: zed("~/repos/zed-industries/zed") },
        { from: "s", to: zed("~/repos/flox/flox") },
        { from: "d", to: zed("~/repos/drizzle-team/drizzle-orm") },
        { from: "f", to: zed("~/repos/jax-ml/jax") },
        { from: "g", to: zed("~/repos/ClickHouse/ClickHouse") },
        { from: "grave_accent_and_tilde", to: zed("~/repos/HelixDB/helix-db") },
        { from: "z", to: zed("~/repos/livestorejs/livestore") },
        { from: "x", to: zed("~/repos/oxc-project/oxc") },
        { from: "c", to: zed("~/repos/tailwindlabs/tailwindcss") },
        { from: "b", to: zed("~/repos/postgres/postgres") },
        { from: "left_command", to: zed("~/repos/tursodatabase/turso") },
        { from: "spacebar", to: zed("~/code/org/1f/gen") },
      ],
      // { from: "v", to: zed("~/repos/pqrs-org/TrueWidget") },
      // { from: "g", to: km("zed: gridchess") }, // todo: move to diff good key
      // { from: "c", to: km("zed: sync") },
      // { from: "v", to: km("zed: reatom") },
      // { from: "b", to: km("warp: sb") },
      //{ from: "q", to: km("zed: helix") },
      // { from: "e", to: km("warp: raycast") },
      // { from: "e", to: km("warp: alfred") },
      // { from: "s", to: zed("~/x/scrape") },
      //{ from: "d", to: km("zed: as") },
      // { from: "d", to: km("zed: genx") },
      // { from: "f", to: km("warp: friendik") },
      //{ from: "f", to: km("warp: la") },
    },

    // ts-mode: TypeScript snippets
    {
      description: "tsdot",
      layer: "ts-mode",
      mappings: [
        {
          from: "a",
          to: [
            "c",
            "o",
            "n",
            "s",
            "o",
            "l",
            "e",
            "period",
            "l",
            "o",
            "g",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        {
          from: "s",
          to: [
            "equal_sign",
            { key: "period", modifiers: "left_shift" },
            "spacebar",
          ],
        },
        { from: "d", to: ["r", "e", "t", "u", "r", "n", "spacebar"] },
        { from: "f", to: ["c", "o", "n", "s", "t", "spacebar"] },
        {
          from: "g",
          to: [
            { key: "f", modifiers: "left_command" },
            "c",
            "o",
            "n",
            "s",
            "o",
            "l",
            "e",
            "period",
            "l",
            "o",
            "g",
            { key: "9", modifiers: "left_shift" },
            "return_or_enter",
          ],
        },
        {
          from: "z",
          to: [
            "spacebar",
            "s",
            "t",
            "y",
            "l",
            "e",
            "equal_sign",
            { key: "open_bracket", modifiers: "left_shift" },
            { key: "open_bracket", modifiers: "left_shift" },
            { key: "close_bracket", modifiers: "left_shift" },
            { key: "close_bracket", modifiers: "left_shift" },
            "left_arrow",
            "left_arrow",
          ],
        },
        {
          from: "x",
          to: [
            "p",
            "r",
            "o",
            "c",
            "e",
            "s",
            "s",
            "period",
            "e",
            "n",
            "v",
            "period",
          ],
        },
        {
          from: "c",
          to: [
            "spacebar",
            "c",
            "l",
            "a",
            "s",
            "s",
            { key: "n", modifiers: "left_shift" },
            "a",
            "m",
            "e",
            "equal_sign",
            { key: "quote", modifiers: "left_shift" },
            { key: "quote", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        { from: "tab", to: ["a", "s", "y", "n", "c", "spacebar"] },
        { from: "escape", to: ["a", "w", "a", "i", "t", "spacebar"] },
        {
          from: "v",
          to: ["t", "y", "p", "e", "s", "c", "r", "i", "p", "t", "spacebar"],
        },
      ],
    },

    // go-mode: Go snippets
    {
      description: "godot",
      layer: "go-mode",
      mappings: [
        { from: "tab", to: km("w: GoDoc") },
        {
          from: "a",
          to: [
            "f",
            "m",
            "t",
            "period",
            { key: "p", modifiers: "left_shift" },
            "r",
            "i",
            "n",
            "t",
            "l",
            "n",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        {
          from: "s",
          to: [
            { key: "semicolon", modifiers: "left_shift" },
            "equal_sign",
            "spacebar",
          ],
        },
        { from: "d", to: ["r", "e", "t", "u", "r", "n", "spacebar"] },
        {
          from: "f",
          to: [
            { key: "f", modifiers: "left_command" },
            "f",
            "m",
            "t",
            "period",
            "p",
            "return_or_enter",
          ],
        },
        {
          from: "g",
          to: [
            "i",
            "f",
            "spacebar",
            "e",
            "r",
            "r",
            "spacebar",
            { key: "1", modifiers: "left_shift" },
            "equal_sign",
            "spacebar",
            "n",
            "i",
            "l",
            "spacebar",
            { key: "open_bracket", modifiers: "left_shift" },
            "return_or_enter",
          ],
        },
        {
          from: "j",
          to: [
            "grave_accent_and_tilde",
            "j",
            "s",
            "o",
            "n",
            { key: "semicolon", modifiers: "left_shift" },
            { key: "quote", modifiers: "left_shift" },
            { key: "quote", modifiers: "left_shift" },
            "grave_accent_and_tilde",
            "left_arrow",
            "left_arrow",
          ],
        },
        {
          from: "z",
          to: [
            "l",
            "o",
            "g",
            "period",
            { key: "p", modifiers: "left_shift" },
            "r",
            "i",
            "n",
            "t",
            "l",
            "n",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        {
          from: "x",
          to: [
            "f",
            "m",
            "t",
            "period",
            { key: "p", modifiers: "left_shift" },
            "r",
            "i",
            "n",
            "t",
            "l",
            "n",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
            { key: "quote", modifiers: "left_shift" },
            "hyphen",
            "hyphen",
          ],
        },
        {
          from: "c",
          to: { key: "semicolon", modifiers: ["left_control", "left_shift"] },
        },
        { from: "v", to: ["g", "o", "l", "a", "n", "g", "spacebar"] },
        {
          from: "b",
          to: [
            "l",
            "o",
            "g",
            "period",
            { key: "f", modifiers: "left_shift" },
            "a",
            "t",
            "a",
            "l",
            { key: "9", modifiers: "left_shift" },
            "e",
            "r",
            "r",
            { key: "0", modifiers: "left_shift" },
          ],
        },
      ],
    },

    // py-mode: Python snippets
    {
      description: "pydot",
      layer: "py-mode",
      mappings: [
        {
          from: "a",
          to: [
            "p",
            "r",
            "i",
            "n",
            "t",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        {
          from: "s",
          to: ["hyphen", { key: "period", modifiers: "left_shift" }],
        },
        { from: "d", to: ["r", "e", "t", "u", "r", "n", "spacebar"] },
        { from: "v", to: ["p", "y", "t", "h", "o", "n", "spacebar"] },
      ],
    },

    // swift-mode: Swift snippets
    {
      description: "swiftdot",
      layer: "swift-mode",
      mappings: [
        {
          from: "a",
          to: [
            "p",
            "r",
            "i",
            "n",
            "t",
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "left_arrow",
          ],
        },
        { from: "v", to: ["s", "w", "i", "f", "t", "spacebar"] },
      ],
    },

    // rust-mode: Rust snippets
    {
      description: "rustdot",
      layer: "rust-mode",
      mappings: [
        {
          from: "a",
          to: [
            "l",
            "o",
            "g",
            { key: "1", modifiers: "left_shift" },
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "semicolon",
            "left_arrow",
            "left_arrow",
          ],
        },
        {
          from: "s",
          to: [
            "a",
            "s",
            "s",
            "e",
            "r",
            "t",
            { key: "hyphen", modifiers: "left_shift" },
            "e",
            "q",
            { key: "1", modifiers: "left_shift" },
            { key: "9", modifiers: "left_shift" },
          ],
        },
        {
          from: "d",
          to: [
            "hyphen",
            { key: "period", modifiers: "left_shift" },
            "spacebar",
          ],
        },
        {
          from: "f",
          to: [
            "p",
            "r",
            "i",
            "n",
            "t",
            "l",
            "n",
            { key: "1", modifiers: "left_shift" },
            { key: "9", modifiers: "left_shift" },
            { key: "0", modifiers: "left_shift" },
            "semicolon",
            "left_arrow",
            "left_arrow",
            { key: "quote", modifiers: "left_shift" },
            { key: "open_bracket", modifiers: "left_shift" },
            { key: "semicolon", modifiers: "left_shift" },
            { key: "slash", modifiers: "left_shift" },
            { key: "close_bracket", modifiers: "left_shift" },
            "right_arrow",
            "comma",
            "spacebar",
          ],
        },
        { from: "v", to: ["r", "u", "s", "t", "spacebar"] },
      ],
    },

    // left-control-mode: gh workspaces
    {
      description: "leftControlKey (gh workspaces)",
      layer: "left-control-mode",
      mappings: [
        { from: "e", to: km("cursor: openai-evals-gh.") },
        { from: "r", to: km("cursor: swift-subprocess-gh.") },
        { from: "t", to: km("cursor: tiktoken-gh.") },
        { from: "y", to: km("cursor: yt-dlp-gh.") },
        { from: "u", to: km("cursor: just-gh.") },
        { from: "i", to: km("cursor: sqlite-utils-gh.") },
        { from: "a", to: km("cursor: optax-gh.") },
        { from: "s", to: km("cursor: datasette-gh.") },
        { from: "d", to: km("cursor: claude-coder-gh.") },
        { from: "f", to: km("cursor: fish-gh.") },
        { from: "h", to: km("cursor: helix-gh.") },
        { from: "j", to: km("cursor: jj-gh.") },
        { from: "k", to: km("cursor: scrapling-gh.") },
        { from: "l", to: km("cursor: simonw-llm-gh.") },
        { from: "semicolon", to: km("cursor: roo-code-gh.") },
        { from: "c", to: km("cursor: claude-code-gh.") },
        { from: "v", to: km("cursor: llvm-gh.") },
        { from: "b", to: km("cursor: blender-gh.") },
        { from: "n", to: km("cursor: tapnet-gh.") },
        { from: "m", to: km("cursor: mujoco-warp-gh.") },
        { from: "period", to: km("cursor: crawl4ai-gh.") },
        { from: "spacebar", to: km("cursor: openai-realtime-agents-gh.") },
      ],
    },

    // left-option-mode: linear
    {
      description: "leftOptionKey (linear)",
      layer: "left-option-mode",
      mappings: [
        { from: "j", to: km("linear: focus initiative") },
        { from: "k", to: km("linear: nikiv") },
        { from: "i", to: km("linear: linsa") },
        { from: "semicolon", to: km("linear: gen") },
      ],
    },

    // spacebar-mode: screenshots & apps
    {
      description: "spacekey",
      layer: "spacebar-mode",
      mappings: [
        {
          from: "1",
          to: {
            key: "q",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "2",
          to: { key: "4", modifiers: ["left_command", "left_shift"] },
        },
        {
          from: "3",
          to: {
            key: "9",
            modifiers: ["left_control", "left_option", "left_shift"],
          },
        },
        {
          from: "4",
          to: { key: "3", modifiers: ["left_command", "left_shift"] },
        },
        { from: "tab", to: km("open: CleanShot") },
        {
          from: "q",
          to: { key: "5", modifiers: ["left_control", "left_option"] },
        },
        {
          from: "w",
          to: { key: "3", modifiers: ["left_control", "left_option"] },
        },
        {
          from: "e",
          to: { key: "2", modifiers: ["left_control", "left_option"] },
        },
        {
          from: "r",
          to: { key: "7", modifiers: ["left_command", "left_shift"] },
        },
        { from: "t", to: km("web: GitHub (personal)") },
        { from: "i", to: km("open: Reader") },
        { from: "o", to: km("open: X Feed (in Arc)") },
        { from: "p", to: km("open: X profile (in Arc)") },
        { from: "escape", to: km("open: Comet") },
        { from: "a", to: km("open: Dia") },
        { from: "s", to: km("open: Preview") },
        { from: "d", to: km("open: Arc") },
        {
          from: "f",
          to: { key: "9", modifiers: ["left_command", "left_shift"] },
        },
        { from: "g", to: km("arc: grokipedia.com") },
        { from: "h", to: km("open: Codex Monitor") },
        { from: "j", to: km("open: Discord") },
        { from: "k", to: km("open: Gen") },
        { from: "l", to: km("open: Telegram") },
        { from: "semicolon", to: km("open: Slack") },
        {
          from: "grave_accent_and_tilde",
          to: km("arc: news.ycombinator/new-comments"),
        },
        { from: "z", to: km("open: IG Messages (in Arc)") },
        { from: "c", to: km("telegram: saved") },
        { from: "v", to: km("open: Glide") },
        { from: "b", to: km("arc: colab.research.google.com") },
        { from: "n", to: km("linear: Plan") },
        { from: "m", to: km("open: X Messages (in Arc)") },
        { from: "comma", to: km("arc: aistudio.google.com (3)") },
        { from: "period", to: km("arc: aistudio.google.com") },
        { from: "slash", to: km("arc: aistudio.google.com (2)") },
      ],
    },
  ],
} satisfies Config
